### ISSUE TITLE
No defined mechanism for embedding image data.

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#159] opened 2016-02-05 00:36 UTC
Even though SMPTE ST2052 supports embedded images via the smpte:image element, IMSC excludes use of that element. Consequently there is no means to embed an image that is defined. It could be the case that one may use the 'data' URL schema, e.g., smpte:backgroundImage="data:..."; however, IMSC does not at present define which URL schemas should be supported.

**Comment by palemieux** [comment] 2016-02-05 01:01
Duplicate of #82

**Closed by palemieux** 2016-02-05 01:01 UTC
Labels: duplicate
