### ISSUE TITLE
Same and cross origin requirements not specified.

### ISSUE THREAD

**Issue by skynavga** [w3c/imsc#158] opened 2016-02-05 00:33 UTC
Since IMSC allows references to external images, the same and cross origin requirements/constraints need to be defined.

**Comment by palemieux** [comment] 2018-01-15 19:04
Blocked by https://github.com/w3c/ttml2/issues/405

**Comment by palemieux** [comment] 2018-01-15 21:40
Duplicate of #280

**Closed** 2018-01-22 20:00 UTC
Labels: duplicate
